modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/Meridanus/fabric_xp_storage_additions/issues"

[[mods]]
modId = "xps_additions"
version = "${version}"
displayName = "XP Obelisk Additions"
description = "This mod add useful things to the XP Obelisk!"
authors = "Meridanus"

[[mixins]]
config = "xps_additions-common.mixins.json"

[[dependencies.xps_additions]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xps_additions]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xps_additions]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.xps_additions]]
modId = "xps"
type = "required"
versionRange = "[0.5.0,)"
ordering = "AFTER"
side = "BOTH"
